engine/config.go
engine/config_test.go
engine/engine.go
flow/flowdef/definition.go

First of a set of Iterative changes to decompose config.json
PooledConfig object now is not read from config.json, default values are used instead.
Environment variables RUNNER_WORKERS and RUNNER_QUEUE_SIZE are used to override the default values

PooledConfig default values and environment variables override values

---

logger/logfactory.go
logger/logger.go

Name based logger implementation for engine, activities and triggers.
The default implementation is based on https://github.com/sirupsen/logrus
It supports:
- Grouping of same type of activities/triggers 
- Setting different log levels for each logger
This approach will allow us to replace https://github.com/sirupsen/logrus implementation with other/better implementation without changing activity/trigger/engine code.
####################**Example**##########################
package main
import (
"github.com/TIBCOSoftware/flogo-lib/logger"
)
func main() {
enggLogger, _ := logger.GetLogger("engine")
enggLogger.Info("This is Engine log message.")
enggLogger.Infof("[%s] %s","Hello There!!", "This is formatted Engine log message.")
logActivityLogger, _ := logger.GetLogger("tibco-log") …

Common library for Engine/Triggers/Activities logs

---

config/config.go
logger/logfactory.go

New environment variable 'LOG_DATETIME_FORMAT' can determine what format to use for date and time logging.
The default format is '2006-01-02 15:04:05.000'.

Pluggable datetime format for logging

---

core/activity/error.go
flow/activity/error.go
flow/flowinst/instance.go

Any error code set by activity developer would be propagated to the engine and then to the error handler.
The default value would be 0.

Added support for error code

---

core/action/registry.go

Locking a mutex on reads was not being done and the wrong mutex was being used on copy.

Safe access fixes for core/action/registry.go

---

app/instances.go
core/trigger/config.go

Added ability to specify output of a trigger or handler in the flogo.json.  If an output isn't specified in the handler, it will try to resolve the value using the trigger output values.
Helper method has been added to HandlerConfig to assist in value resolution:
func (hc *HandlerConfig) GetOutput(name string) interface{}

add support for setting output on triggers in flogo.json

---

core/activity/activity.go
core/activity/registry.go
core/activity/registry_test.go
core/data/path.go
core/data/path_test.go
core/expr/resolver.go
core/property/registry.go
core/trigger/registry.go

Support new syntax on input mapper and branch conditions:
New format explained here: http://confluence.tibco.com/display/FLOGO/Architecture#Architecture-ExpressionSyntaxProposal
This solution is backward compatible with old format.

Support new resolver syntax

---

core/mapper/exprmapper/function/number/random/random.go
core/mapper/exprmapper/function/number/random/random_test.go
core/mapper/exprmapper/function/string/concat/concat.go
core/mapper/exprmapper/function/string/concat/concat_test.go
core/mapper/exprmapper/function/string/equals/equals.go
core/mapper/exprmapper/function/string/equals/equals_test.go
core/mapper/exprmapper/function/string/length/length.go
core/mapper/exprmapper/function/string/length/length_test.go

I going to add some `string` and `number` static functions to show how to use the function in expr mapper, especially in documentation.
Functions
```
string.length("str")
string.equals("str1", "str2", ignorecase)
string.concat("str1","str2","str3"...)
number.random(100)
```

Add couple of static functions

---

core/mapper/exprmapper/expression/expr/expr.go
core/mapper/exprmapper/expression/expression_test.go

1. Remove `=` for equals to only use `==`
2.  Change `&` to `&&` for operator `and`

Operator should be == and && not = or & meanwhile add more strict test cases

---

core/trigger/handler.go

When a trigger input attr is an object, but a string is passed rather than a json obj no issue is currently logged and future mappings that rely on the trigger->flow inputs do not work.
For now, just grabbing the coercion error, logging and bubbling it up.

logging and bubbling up error when failing to parse trigger input attrs

---

core/data/path.go
core/data/resolve.go
core/data/resolve_test.go
core/mapper/exprmapper/json/field/field.go
core/mapper/exprmapper/ref/mappingref.go

The PR to fix the issue to map current scope data in action mapping.   such as map rest trigger header or body into flow input or map flow output to trigger output.
Sample trigger mapping.
```json
{
"mappings": {
"input": [
{
"mapTo": "inputparam",
"type": "expression",
"value": "$.headers.Accept"
},
{
"mapTo": "inputparam2",
"type": "assign",
"value": "$.body[0].name"
},
{
"mapTo": "inputparam3",
"type": "assign",
"value": "$.body"
}
],
"output": [
{
"mapTo": "$INPUT['data']['replymessage']",
"type": "expression",
"value": "$.outputparam"
},
{
"mapTo": "data.replymessage2",
"type": "assign",
"value": "$.outputparam2"
},
{
"mapTo": "data.replymessage3[0]",
"type": "expression",
"value": "$.outputparam3"
},
{
"mapTo": "$INPUT['code']",
"type": "expression",
"value": 200
}
]
}
}
```

Handle $. to get current scope attr data

---

core/trigger/handler.go

Today, action mappings are not evaluated if trigger has no output.
Since, value could be hardcoded and not referenced from the trigger, runtime should evaluate such mappings.

Action mapping should be evaluated irrespective of trigger output

---

core/trigger/handler.go

Fixes: # .
```
[*] Bugfix
[] Feature
```
Action metadata attr cannot be found in scope while there is no action input mapper
Add action metadata into scope no matter it has action input mapper or not.

Add action metadata into inputs no matter has input mapper or not

---

core/mapper/exprmapper/exprmapper.go
core/mapper/exprmapper/function/string/equals/equals.go
core/mapper/exprmapper/function/string/equals/equals_test.go
core/mapper/exprmapper/function/string/equalsignorecase/equalsignorecase.go
core/mapper/exprmapper/function/string/equalsignorecase/equalsignorecase_test.go

Fixes: #151 
```
[x] Bugfix
[] Feature
```

Pre-registry all functions

---

logger/exported.go
logger/logfactory.go

Fixes: TIBCOSoftware/flogo#204 .
```
[X] Bugfix
[] Feature
```
For invalid log level, nil is returned which causes downstream code to throw error.
For invalid log level, it will use default log level.
Unsupported Log Level - [INF0]. Set to Log Level - [INFO]

Use default log level when invalid value is set

---

core/mapper/exprmapper/expression/gocc/flogo.bnf
core/mapper/exprmapper/expression/gocc/parser/actiontable.go
core/mapper/exprmapper/expression/gocc/parser/gototable.go
core/mapper/exprmapper/expression/gocc/parser/parser.go
core/mapper/exprmapper/expression/gocc/parser/productionstable.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #152 
Does not support this case: `string.equals("sea", "sea") == true` or `isDefined($activity[rest_2].result.photoUrlz) != false`
Support expression like: `isDefined($activity[rest_2].result.photoUrlz) != false` or `string.equals("seafood,name", "sea") == false`

Expression support boolean to fix #152

---

core/activity/metadata.go
core/activity/registry.go
core/trigger/metadata.go
engine/engine.go

```
[] Bugfix
[X] Feature
```
**Fixes**: # https://github.com/TIBCOSoftware/flogo/issues/216
**What is the current behavior?** The current version doesn't output debug statements of the versions of the triggers and activities
**What is the new behavior?** If the loglevel is set to debug it will print for activities:
```
Registering activity [ github.com/TIBCOSoftware/flogo-contrib/activity/log ] which has version [ 0.0.1 ]
```
and for triggers it will print
```
Trigger [ my_rest_trigger ] has ref [ github.com/TIBCOSoftware/flogo-contrib/trigger/rest ] and version [ 0.0.1 ]
```

Logging metadata for activity and trigger

---

core/mapper/exprmapper/function/string/substring/substring.go
core/mapper/exprmapper/function/string/substring/substring_test.go

```
[] Bugfix
[X] Feature
```
**What is the current behavior?** No function for substring exists
```
string.substring(string, int, int)
string : input string
int : starting position for substring
int : length of the substring
```
string.substring("Flogo is the most awesome project ever", 0, 5) would produce "Flogo"

Added substring function

---

core/mapper/exprmapper/exprmapper.go

```
[X] Bugfix
[X] Feature
```
_In my original PR (#175) to introduce substring, I didn't add the import into `exprmapper.go`. This PR fixes that and makes the substring available for use by the engine_

Adding substring in exprmapper so it can be used

---

core/mapper/exprmapper/exprmapper.go
core/mapper/exprmapper/function/array/length/length.go
core/mapper/exprmapper/function/array/length/length_test.go

```
[] Bugfix
[X] Feature
```
**Fixes**: https://github.com/TIBCOSoftware/flogo/issues/282
**What is the current behavior?** You cannot use the length of an array in a function
**What is the new behavior?** This introduces the `array.length()` function which will return the length of an array
```go
// Executing it on this array would produce 3
arr := []string{"1", "2", "3"}
// Executing it on this array produces 5
arr2 := []int{1, 2, 3, 4, 5}
```

Added array length function

---

core/mapper/exprmapper/expression/expression.go

```
[] Bugfix
[] Feature
[*] Other... Please describe: Remove a warn log which is unless
```
**Fixes**: #
For expression mapping, it always prints warn message if it is not an expression.
No, warn log anymore

Remove unnecessary Warn log

---

util/managed/managed.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
The engine did not print any error to console while panic occurred at service/trigger start
Throw the panic recover out

throw error out/print to console while panic happen in service start

---

core/data/attribute.go

```
[x] Bugfix
[] Feature
```
**Fixes**: #
For non string type properties, when value is set to env, runtime fails due to type incompatibility as value is not resolved appropriately. 
`
{
"name": "MAX_COUNT",
"type": "integer",
"value": "$env.MAX_COUNT"
}
`
Before coercing value, env var is resolved using appropriate resolver.

Resolving env reference in property value

---

engine/engine.go

```
[x] Bugfix
[] Feature
```
**Fixes**: #
When starting an application, output log looks like:
```
2018-10-19 11:22:40.724 INFO   [engine] - Starting app [ %s ] with version [ %s ]app-name0.0.1
2018-10-19 11:22:40.724 INFO   [engine] - Engine Starting...
2018-10-19 11:22:40.728 INFO   [engine] - Starting Services...
2018-10-19 11:22:40.728 INFO   [engine] - Started Services
```
When starting an application, output log looks like:
```
2018-10-19 11:22:40.724 INFO   [engine] - Starting app [ app-name ] with version [ 0.0.1 ] …
```

Fix a typo on logger (logs without formatting)

---

core/trigger/config.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Now we only support app property for trigger settings through getSetting method which just returns string.
We have cases that setting returns a complex value or a bool, not the only string.  Take example we have code to get setting through `handler.Settings["Path"]`, the way we have the issue to handle app properties.
Handle app property while unmarshaling the app.

Handle app property in trigger settings

---

core/mapper/exprmapper/expression/expr/expr.go
core/mapper/exprmapper/expression/expression_test.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #245 
Currently, we convert the right part value to left type base on left type on condition expression which will have an issue when int compare with float(int at left side).
New behavior,  convert any integer to float if there is a float in condition expression.

Fixed #245, convert int to float once there is int comparing with float.

---

core/mapper/exprmapper/json/field/field.go
core/mapper/exprmapper/json/field/field_test.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Have an issue to support field name has double or single quotes. such as: `'apostoph`
Make sure parser has the ability to handle this case.

Handle single and double quotes in field name

---

app/config.go
app/property.go
app/property_test.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
Value resolver returns error. To follow semantics like os.Lookup() where value is return with bool flag to indicate whether value is indeed found or not.
This change also includes lookup based on app property name.
Makes it consistent with Go semantics. Also, makes it easy for developers to resolve app prop value using app prop name.

Value resolver to return bool instead error to indicate whether value is resolved or not

---

app/config.go
app/property_test.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
Currently, users can not chain property resolvers e.g. FLOGO_APP_PROPS_RESOLVERS=env,json,consul
App property resolution mechanism now supports comma separated list of resolvers. Now runtime will attempt to resolve app property using all configured resolvers.

Chaining of resolvers
