engine/runner/direct_test.go
flow/flowinst/instance_ser_test.go

Added tests to direct runner, also commented out broken tests in instance

Add tests to direct runner 100% coverage

---

engine/engine.go
engine/runner/direct.go
engine/runner/pooled.go
engine/runner/pooled_test.go
engine/runner/worker.go

Added tests for pooled runner, also changed NewDirectRunner to NewDirect and NewPooledRunner to NewPooled to follow golang conventions

Add pooled tests 100% coverage and change runner New() constructs

---

flow/service/tester/request.go

Fix issue with renaming NewDirectRunner to NewDirect

Rename NewDirectRunner to NewDirect

---

engine/runner/direct_test.go

Fix a couple of runner conflicts among tests due to changes.

Fix direct runner tests

---

engine/runner/worker.go
engine/runner/worker_test.go

Added a set of tests for Worker, added case for invalid request type

Add worker tests

---

config/config.go
engine/config.go
engine/config_test.go

closes https://github.com/TIBCOSoftware/flogo-lib/issues/19
Move default config values to config.go and use defaults for LogLevel overridable by env variables.

Move default config values to config.go

---

config/config.go
engine/engine.go
engine/engine_test.go
types/app.go

Create new engine that will support app implementation

Add New Engine for apps

---

app/instances.go
app/instances_test.go
core/trigger/registry.go
engine/engine.go
types/app.go

Added an instance manager that will create instances for a registered trigger type according to the app triggers.

Add Trigger instances manager

---

app/instances.go
app/instances_test.go
core/trigger/registry.go

Creation of Trigger instances according to flogo.json

Deep copy of trigger.Trigger

---

app/instances.go
core/trigger/registry.go
core/trigger/trigger.go
engine/engine.go
types/app.go

Engine now start new Triggers from flogo.json if Trigger2 interface is implemented and new Registry is used to register Triggers

Start Triggers

---

app/instances.go
app/instances_test.go
core/action/action.go
core/action/registry.go
core/trigger/registry.go
engine/engine_test.go

Add Actions registry

---

core/trigger/registry.go
flow/flowinst/instance.go
flow/service/tester/service.go

Now the flow model gets passed to the instance.

Add Flow model Instance contribution

---

core/data/mapping.go

Existing FLOGO mapper does not handle array node in the expressions like {T.content}.**Product[1]**.warehouseLocation.latitude or {T.content}.**Product[0]**.**tags[1]**
This change recursively looks for arrays and resolve to appropriate object.
{
"Product":[
{
"id": 2,
"name": "An ice sculpture",
"price": 12.50,
"tags": ["cold", "ice"],
"dimensions": {
"length": 7.0,
"width": 12.0,
"height": 9.5
},
"warehouseLocation": {
"latitude": -78.75,
"longitude": 20.4
}
},
{
"id": 3,
"name": "A blue mouse",
"price": 25.50,
"dimensions": {
"length": 3.1,
"width": 1.0,
"height": 1.0
},
"warehouseLocation": {
"latitude": 54.4,
"longitude": -32.7
}
}
]
}
{ 
"name":"RestReplyApp",
"version":"0.0.1",
"type":"wi",
"description":"REST Reply application",
"triggers":[ 
{ 
"id":"my_timer_trigger", …

Resolving array in mapping expression

---

app/instances.go
core/action/registry.go
core/trigger/registry.go
engine/engine.go
engine/runner/direct.go
engine/runner/pooled.go
engine/runner/worker.go
flow/flowdef/definition.go
flow/flowinst/action.go
flow/flowinst/data.go
flow/flowinst/exec.go
flow/flowinst/instance.go
flow/model/model.go
flow/script/fggos/linkexpr.go
flow/service/flowprovider/service.go
flow/service/staterecorder/service.go
flow/service/tester/request.go
flow/service/tester/service.go
flow/support/embedded.go
flow/test/model.go
logger/exported.go
logger/logfactory.go
logger/logger.go
util/managed.go
util/utils.go

Added log default implementation.
This will use the logger default implementation for flogo-lib.

Add Log implementation

---

core/data/types.go
flow/flowdef/expr.go
flow/script/fggos/linkexpr.go
flow/service/flowprovider/service.go

enhance support for plugable link expression evaluation

---

core/trigger/registry.go
core/trigger/trigger.go
engine/engine.go

Added new function to collect trigger instance info about its current state and error (if reported)

Collecting trigger runtime status and error for monitoring/ping implementation

---

flow/activity/metadata.go
flow/flowdef/definition.go
flow/flowdef/definition_ser.go

This will enable activityRef in lib

Enable activityRef

---

core/trigger/metadata.go
flow/activity/metadata.go

This will allow the engine to get the trigger id from the metadata using ref.

Make triggers ref aware

---

app/serializer.go

Created the new Interface that will be implemented by the extension for the serializer.
Also created the default implementation for when the extension is not provided.

Add app serializer interface and default implementation

---

config/config.go

Change env variables keys to . notation

Change env variables keys

---

app/config.go
core/data/environment.go
core/data/environment_test.go
core/property/registry.go
core/property/registry_test.go
engine/engine.go

Added properties implementation for engine.

Propertybag

---

core/data/coercion.go

Change to handle conversion of stringified JSON to Object

String to Object conversion

---

core/data/coercion.go

String to Array conversion

---

core/data/path.go
core/data/path_test.go
core/property/registry.go

Changes to support property resolution

Property resolution in activity mapping

---

engine/engine.go

Cleaning unused old engine struct and constructor.

Cleanup old engine code

---

config/config.go
engine/engine.go

Separate engine init from start

Entrypoint

---

core/trigger/config.go

New Configuration:
```
"handlers": [
{
"actionId": "my_simple_flow",
"settings": {
"method": "GET",
"path": "/test"
},
"actionMappings" : {
"input":[
],
"output": [
]
}
}
]
```

update trigger mapping config

---

core/action/metadata.go
core/activity/metadata.go
core/data/coercion.go
core/data/data.go
core/data/resolve.go
core/data/scope.go
core/mapper/mapper_test.go
core/mapper/util.go
core/trigger/config.go
core/trigger/metadata.go
engine/runner/direct.go
engine/runner/direct_test.go
engine/runner/pooled.go
engine/runner/pooled_test.go
engine/runner/util.go
engine/runner/worker_test.go

Use functions to access attribute data members and do type conversion automatically for attribute values

Attribute cleanup

---

core/data/resolve.go
core/trigger/config.go

Allow users to reference properties and environment variables using $env and $property resolvers.

fix for issue #123

---

core/data/attribute.go

With this PR json.Marshal() generates flogo.json properly (in specific action's metadata section).

Add MarshalJSON support for action's metadata

---

config/config.go
core/trigger/trigger.go
engine/config.go
engine/config_test.go
engine/engine.go
logger/exported.go
logger/logger.go
util/managed/managed.go
util/managed/status.go
util/service.go

Cleanup "managed" support and add ability to get the startup information on triggers from the engine.

clean up managed and add ability to retrieve trigger startup info

---

core/mapper/exprmapper/arraymapping.go
core/mapper/exprmapper/ref/mappingref.go

Array mapping has a problem on object/any field but it working with WI case(complex_object field).

Fixed array mapping on un-complex_object field

---

core/action/action.go
core/action/config.go
core/action/registry.go
core/activity/activity.go
core/activity/context.go
core/data/coercion.go
core/trigger/config.go
core/trigger/legacy.go
core/trigger/trigger.go
engine/runner/direct.go
engine/runner/pooled.go

Cleanup deprecation comments in the code

cleanup deprecation comments

---

core/data/path.go
core/data/scope.go

The value lookup/set code only handles object and params type.
It should handle complex object.

Handle complex object value

---

core/mapper/exprmapper/expression/function/function.go

Fixes: # .
```
[*] Bugfix
[] Feature
```
Having issue to support functions in action mapping such as: string.concat($.content,"abc")
Support it.

Function support get from current data scope

---

core/data/coercion.go
core/data/path.go
core/data/path_test.go
core/mapper/mapper_test.go
logger/exported.go
logger/logfactory.go
logger/logger.go

```
[x] Bugfix
[] Feature
```
**Fixes**: TIBCOSoftware/flogo#212 
Avoid converting arrays and slices when not needed

Array handling

---

logger/exported.go
logger/logfactory.go
logger/logger.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
Adds the ability to get the current log level of the default logger

add ability to get the default logger's log level

---

app/config.go
app/property.go
core/data/resolve.go
core/data/resolve_test.go
engine/engine.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
1. Handles new properties model as described at https://github.com/TIBCOSoftware/flogo/wiki/Application-Properties
2. Updated resolver to handle $property[VAR] and $env[VAR]
3. Added resolution logic for property value e.g. value now can be sourced from $env[VAR]
`
{
"name": "PROP_BOOL",
"type": "boolean",
"value": "$env[BOOL_ENV_VAR]"
}
`
Following properties will be handled at runtime:
`"properties": [
{
"name": "PROP_BOOL",
"type": "boolean",
"value": true
},
{
"name": …

Changes for new properties model

---

core/trigger/handler.go

```
[x] Bugfix
[] Feature
```
**Fixes**: #
#173 

Added API to access handler output

---

core/data/path.go

```
[] Bugfix
[x] Feature
```
**Fixes**: TIBCOSoftware/flogo#272
**What is the new behavior?** Add the ability to resolve field values in go structs

fix for TIBCOSoftware/flogo#272

---

engine/runner/worker.go

```
[x] Bugfix
[] Feature
```
**Fixes**: #181 

Fix for Issue #181 - fix worker thread so it can complete

---

core/mapper/exprmapper/json/gabs.go

```
[*] Bugfix
[] Feature
```
**Fixes**: https://github.com/TIBCOSoftware/flogo/issues/281
Have issue support array on root which is not a []interface
No issue so far.

Fixed issue https://github.com/TIBCOSoftware/flogo/issues/281

---

core/mapper/exprmapper/json/gabs.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Have issue to support params type in expression mapping.

Fix an issue to support params in expression type

---

core/mapper/exprmapper/arraymapping.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Having issue to run an array mapping

Just return nil which by mistake latest release refactor

---

engine/runner/worker.go

```
[x] Bugfix
[] Feature
```
**Fixes**: A timing issue observed when flow is replying 

fix timing issue with flow replies

---

core/mapper/exprmapper/expression/expr/expr.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
The expression cannot handle json.number
Expression take json.number as long in expression comparison.

Handle json number in expression

---

core/mapper/exprmapper/arraymapping.go
core/mapper/exprmapper/json/get.go
core/mapper/exprmapper/json/get_test.go
core/mapper/exprmapper/ref/mappingref.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Having issue when get map data from a struct(not a json map or string)
Revert part of PR #177.  we will handle it more details next release.

Revert part of changes for PR #177

---

core/mapper/exprmapper/arraymapping.go
core/mapper/exprmapper/expression/function/function.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Having issue to run a function inside an array mapping

fix cannot run function in array mapping

---

core/mapper/exprmapper/expression/function/function.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
There are some issues that type mismatch happen while calling functions. such as: using float64 for a string.    For complex object attributes mapping which not easy to keep field types so just convert to required type when call function.
The function call will handle argument type stuff

ensure function arguments before call function

---

core/data/attribute.go
core/data/coercion.go
core/data/coercion_test.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
Any string value with prefix **"SECRET:"** will be treated as secret and will be decoded using registered secret handler.

Handling secret value resolution in generic way

---

app/config.go
core/data/attribute.go
core/data/coercion.go
core/data/coercion_test.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
Added app config preprocessing to resolve secrets once

Added secret resolution in app config preprocessing

---

core/trigger/config.go
core/trigger/context.go
core/trigger/handler.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
**What is the new behavior?** 
Adds the ability to set an optional name to handlers and also as that information to the context

add support for optional handler name and add handler info to context

---

app/config.go
app/instances.go
core/action/config.go
core/trigger/config.go
engine/engine.go
flogo/support.go

```
[] Bugfix
[x] Feature
```
**Fixes**: https://github.com/TIBCOSoftware/flogo-contrib/issues/269
Cannot refer to the same instance of an action
You can have toplevel action entries that can be referred to by ID
Updated App Model:
https://github.com/TIBCOSoftware/flogo/wiki/App-Model

add support for shared action instances

---

engine/engine.go

…th engine start/stop
```
[] Bugfix
[x] Feature
```
**Fixes**: #
https://github.com/TIBCOSoftware/flogo/issues/326
No mechanism to start/stop entities based on engine start/stop
With this feature, any entity/object who wish to be life-cycled along with engine life cycle (start/stop) can register implementation of **managed.Managed** with engine. When engine starts or stops, it will call `Start` or `Stop` accordingly.

Added API to register manageable entities which can be life cycled with engine start/stop

---

core/mapper/exprmapper/json/special.go

…
```
[*] Bugfix
[] Feature
```
**Fixes**: #
Have an issue to map root array with special character field mapping
Fix it.

Fix mapping issue for case $activity[activityName].output[0]["abc csd/s"]

---

core/action/metadata.go
core/data/scope.go
core/trigger/handler.go

```
[x] Bugfix
[] Feature
```
**Fixes**: lack of action metadata

enhance action metadata

---

core/activity/async.go
core/activity/context.go
core/trigger/metadata.go
flogo/support.go

```
[] Bugfix
[x] Feature
```
**Fixes**: Add support for activity level shared temporary data.
**What is the new behavior?** Transient shared acitivity specific data is now accessible via the activity.Context.  This can be to store transient information that needs to be access across executions

Activity shared data

---

config/config.go
logger/logfactory.go

```
[] Bugfix
[x] Feature
```
**Fixes**: github.com/TIBCOSoftware/flogo/issues/367
If you set the env variable FLOGO_LOG_FORMAT to "JSON", the json formatter will be used for logging

add support for logging in json format

---

core/mapper/exprmapper/arraymapperr_test.go
core/mapper/exprmapper/expression/function/function.go
core/mapper/exprmapper/exprmapper_test.go

```
[] Bugfix
[] Feature
[*] Other... Please describe:
Add test case for expression mapper and array mapping to void more regression.
```
**Fixes**: #
No good test cases to cover most of the cases for expression mapper and array mapper
Added go test cases

Add test cases for expression mapper and array mapper

---

core/data/resolve.go
core/mapper/exprmapper/expression/function_test.go

```
[] Bugfix
[] Feature
[X] Other... Please describe: Fix typos in code
```
Fixing two typos in the code (one in a comment and one in a panic message)

Fixing typos

---

app/config.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
https://github.com/TIBCOSoftware/flogo/issues/323
There is no way to get name and version of given app in the runtime.
Added two functions to get app name and version.

New functions to get app name and version

---

core/mapper/exprmapper/ref/mappingref.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Have an issue to support property in expression mapper
Fixed it.

Fix property has issue in expression mapper

---

logger/logfactory.go

```
[] Bugfix
[] Feature
[x] Refactoring (no functional changes, no api changes)
```
**Fixes**: #

Updating the Sirupsen import.

---

core/trigger/config.go

```
[x] Bugfix
[] Feature
```
**Fixes**: #236 

Fixes #236

---

config/config.go
core/event/events.go
core/events/events.go

```
[] Bugfix
[x] Feature
```
**Fixes**: #
No support for events
With this change, listeners can be registered to get access to events. Some events are action specific and action should publish appropriate events. Users can implement **EventListener** interface and register it with interested events. 
In below example, SampleListerner is registered to receive Flow and Task events generated by Flow action.
```
package main
import (
"github.com/TIBCOSoftware/flogo-lib/logger"
core "github.com/TIBCOSoftware/flogo-lib/core/event" …
```

Adding event listeners support in core

---

core/mapper/exprmapper/expression/direction/direction.go
core/mapper/exprmapper/expression/expr/expr.go
core/mapper/exprmapper/expression/function/function.go
core/mapper/exprmapper/exprmapper.go
core/mapper/exprmapper/json/get.go
core/mapper/exprmapper/ref/mappingref.go

```
[] Bugfix
[] Feature
[*] Refactoring (no functional changes, no api changes)
```
**Fixes**: #
It prints lots of debug log which is unnecessary and confusion
Make debug log more clearly

Remove bad log and make debug log more cleary for expr mapper

---

logger/exported.go
logger/logfactory.go
logger/zaplogger.go

```
[] Bugfix
[x] Feature
```
**Fixes**: Poor logger performance
Adds the ability to use uber's zap logger via env variable FLOGO_LOGGER_IMPL set to "zap"

Zap logger

---

core/mapper/exprmapper/json/field/field.go
core/mapper/exprmapper/json/field/field_test.go

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Space in ref will be skipped by parser
Keep all space in ref.

Do not skip space for ref parser

---

.travis.yml

```
[*] Bugfix
[] Feature
```
**Fixes**: #
Travis build broke

Fix travis issue to update go version to 1.9.4

---

core/mapper/exprmapper/expression/direction/direction.go
core/mapper/exprmapper/expression/expr/expr.go
core/mapper/exprmapper/expression/expression_test.go
core/mapper/exprmapper/expression/gocc/flogo.bnf
core/mapper/exprmapper/expression/gocc/parser/actiontable.go
core/mapper/exprmapper/expression/gocc/parser/gototable.go
core/mapper/exprmapper/expression/gocc/parser/parser.go
core/mapper/exprmapper/expression/gocc/parser/productionstable.go

```
[] Bugfix
[*] Feature
```
**Fixes**: 
Related to #254, we are not going to support if/else script but it is required to support nested ternary to support kind of #254 cases.
So far we are not supporting nested ternary expression. 
Nesting ternary expression supporting by now.

Support nested ternary expression
